// Curated emoji dataset for the picker.
// Each entry: [char, name, keywords] — keywords include the name words so
// plain substring search just works; extra synonyms widen recall.
// Categories: Smileys · People · Animals · Food · Activity · Travel · Objects · Symbols
.pragma library

const categories = [
    "Smileys", "People", "Animals", "Food", "Activity", "Travel", "Objects", "Symbols"
];

const emoji = [
    // ── Smileys ──
    ["😀", "grinning face", "smile happy joy grin"],
    ["😃", "smiling face big eyes", "smile happy joy"],
    ["😄", "smiling face smiling eyes", "smile happy joy laugh"],
    ["😁", "beaming face smiling eyes", "grin happy"],
    ["😆", "squinting face", "laugh haha xd"],
    ["😅", "grinning sweat", "hot nervous laugh"],
    ["🤣", "rolling on floor laughing", "rofl lol laugh"],
    ["😂", "face tears of joy", "lol cry laugh crying"],
    ["🙂", "slightly smiling face", "smile ok"],
    ["🙃", "upside down face", "silly sarcasm"],
    ["😉", "winking face", "wink flirt"],
    ["😊", "smiling face smiling eyes blush", "happy warm shy"],
    ["😇", "smiling face halo", "angel innocent"],
    ["🥰", "smiling face hearts", "love adore crush"],
    ["😍", "heart eyes love", "love crush admire"],
    ["🤩", "star struck", "excited wow amazing"],
    ["😘", "kiss heart", "love kiss"],
    ["😗", "kissing face", "kiss"],
    ["😎", "smiling face sunglasses cool", "cool chill"],
    ["🤓", "nerd face glasses", "geek nerd smart"],
    ["🧐", "face monocle", "inspect curious"],
    ["😏", "smirking face", "smug flirt sly"],
    ["😒", "unamused face", "meh annoyed bored"],
    ["😞", "disappointed face", "sad down"],
    ["😔", "pensive face", "sad thoughtful sorry"],
    ["😟", "worried face", "concern nervous"],
    ["🙁", "slightly frowning face", "sad frown"],
    ["☹️", "frowning face", "sad unhappy"],
    ["😣", "persevering face", "struggle helpless"],
    ["😖", "confounded face", "confused upset"],
    ["😫", "tired face", "exhausted weary"],
    ["😩", "weary face", "tired drained"],
    ["🥺", "pleading face", "please beg puppy eyes"],
    ["😢", "crying face", "tear sad cry"],
    ["😭", "loudly crying face", "sob bawling tears"],
    ["😤", "triumph steam nose", "angry determined huff"],
    ["😠", "angry face", "mad upset"],
    ["😡", "rage red face", "angry furious mad"],
    ["🤬", "cursing mouth symbols", "swear angry"],
    ["🤯", "exploding head mind blown", "shock wow mindblown"],
    ["😳", "flushed face", "embarrassed blush surprised"],
    ["🥵", "hot face", "heat sweating summer"],
    ["🥶", "cold face", "freeze winter ice"],
    ["😱", "scream fear", "shock scared horror"],
    ["😨", "fearful face", "scared worried shock"],
    ["😰", "anxious sweat", "nervous afraid"],
    ["🤗", "hugging face", "hug thanks warm"],
    ["🤔", "thinking face", "hmm consider ponder"],
    ["🤭", "hand over mouth", "giggle oops whoops"],
    ["🤫", "shushing face", "quiet shh secret"],
    ["🤥", "lying pinocchio nose", "lie liar"],
    ["😶", "expressionless face", "blank nothing"],
    ["😐", "neutral face", "meh blank"],
    ["😑", "expressionless flat", "deadpan meh"],
    ["😬", "grimacing face", "awkward yikes cringe"],
    ["🙄", "rolling eyes", "eyeroll whatever annoyed"],
    ["😮", "open mouth surprise", "wow surprise gasp"],
    ["😯", "hushed face", "surprised quiet"],
    ["😴", "sleeping zzz", "sleep tired bed"],
    ["🤤", "drooling face", "desire yum hungry"],
    ["😪", "sleepy snot bubble", "tired sleepy"],
    ["😵", "knocked out dizzy", "dead faint dizzy"],
    ["🤐", "zipper mouth", "quiet secret zip"],
    ["🤢", "nauseated green", "sick gross queasy"],
    ["🤮", "vomit throwing up", "sick puke gross"],
    ["🤧", "sneezing tissue", "sick allergy sneeze"],
    ["😷", "medical mask", "sick covid mask"],
    ["🤒", "thermometer fever", "sick temperature ill"],
    ["🤕", "bandage head injury", "hurt injured"],
    ["🤑", "money mouth", "rich greedy cash"],
    ["🤠", "cowboy hat", "western hat"],
    ["😈", "devil purple horns", "evil mischief devil"],
    ["👿", "imp angry devil", "evil demon angry"],
    ["🤡", "clown", "circus joke clown"],
    ["💀", "skull dead", "death skeleton poison"],
    ["☠️", "crossbones skull", "danger death pirate"],
    ["👻", "ghost", "halloween boo spooky"],
    ["👽", "alien", "ufo space extraterrestrial"],
    ["🤖", "robot", "bot ai machine"],
    ["💩", "pile poop", "crap bad"],
    ["😺", "cat smile", "happy cat"],
    ["😹", "cat tears joy", "lol cat laugh"],

    // ── People ──
    ["👋", "waving hand hello", "hi bye wave"],
    ["🤚", "raised back hand", "stop hand"],
    ["✋", "raised hand stop", "high five stop"],
    ["🖖", "vulcan salute spock", "star trek"],
    ["👌", "ok hand perfect", "okay nice perfect"],
    ["🤌", "pinched fingers italian", "maestro what"],
    ["✌️", "victory peace hand", "peace two win"],
    ["🤞", "crossed fingers luck", "hope lucky"],
    ["🤟", "love you gesture", "ily rock"],
    ["🤘", "sign horns rock", "metal rock on"],
    ["🤙", "call me hand", "shaka hang loose"],
    ["👈", "point left", "direction there"],
    ["👉", "point right", "direction this"],
    ["👆", "point up", "above finger"],
    ["👇", "point down", "below finger"],
    ["👍", "thumbs up like approve", "yes good ok like"],
    ["👎", "thumbs down dislike", "no bad dislike"],
    ["✊", "raise fist power", "solidarity punch bump"],
    ["👊", "oncoming fist punch", "bump fight bro"],
    ["👏", "clapping hands applause", "bravo praise clap"],
    ["🙌", "raising hands celebrate", "hooray praise hype"],
    ["👐", "open hands", "hug open"],
    ["🤲", "palms up together", "pray cupped offer"],
    ["🙏", "folded hands pray thanks", "please thank you pray"],
    ["💪", "flexed biceps strong", "muscle strong gym"],
    ["🧠", "brain", "smart mind think"],
    ["👀", "eyes looking", "watch see look"],
    ["👁️", "eye", "look see watch"],
    ["👄", "mouth lips", "kiss talk"],
    ["🦷", "tooth", "teeth dentist"],
    ["👅", "tongue taste lick", "tongue playful silly"],
    ["👶", "baby", "infant child newborn"],
    ["🧑", "person neutral", "human adult"],
    ["👨", "man", "male guy"],
    ["👩", "woman", "female lady"],
    ["🧓", "older person", "elder grandpa grandma"],
    ["🙋", "raising hand question", "me pick volunteer"],
    ["🙆", "person gesturing ok", "yes correct"],
    ["🙅", "gesturing no", "no deny stop"],
    ["💁", "tipping hand sass", "info whatever sassy"],
    ["🙋‍♂️", "man raising hand", "question volunteer"],
    ["🤷", "shrug idk", "dont know whatever shrug"],
    ["🤦", "face palm", "smh disbelief fail"],
    ["💃", "woman dancing", "dance party salsa"],
    ["🕺", "man dancing", "dance disco party"],
    ["👯", "bunny ears party", "friends dance besties"],
    ["🚶", "walking person", "walk pedestrian"],
    ["🏃", "running person", "run jog marathon hurry"],
    ["🧘", "lotus meditation yoga", "zen calm meditate"],
    ["🛀", "bath tub person", "relax clean bath"],
    ["🤝", "handshake deal", "agreement meet shake"],
    ["👑", "crown king queen", "royal leader best"],

    // ── Animals ──
    ["🐶", "dog puppy", "pet doggo woof"],
    ["🐱", "cat kitten", "pet meow"],
    ["🐭", "mouse", "rodent squeak"],
    ["🐹", "hamster", "pet rodent"],
    ["🐰", "rabbit bunny", "hare easter"],
    ["🦊", "fox", "sly orange"],
    ["🐻", "bear", "teddy grizzly"],
    ["🐼", "panda", "bamboo china"],
    ["🐨", "koala", "australia marsupial"],
    ["🐯", "tiger", "stripes predator"],
    ["🦁", "lion", "king mane brave"],
    ["🐮", "cow", "moo cattle ox"],
    ["🐷", "pig", "piggy pork oink"],
    ["🐸", "frog", "toad ribbit pepe"],
    ["🐵", "monkey face", "ape primate"],
    ["🙈", "see no evil monkey", "hide embarrassed cover"],
    ["🙉", "hear no evil monkey", "ignore ears"],
    ["🙊", "speak no evil monkey", "quiet secret shut"],
    ["🐔", "chicken", "hen poultry cluck"],
    ["🐧", "penguin", "antarctica cold tuxedo"],
    ["🐦", "bird", "tweet fly chirp"],
    ["🐤", "baby chick", "bird yellow cute"],
    ["🦆", "duck", "pond quack"],
    ["🦅", "eagle", "hawk bird prey freedom"],
    ["🦉", "owl", "night wise hoot"],
    ["🦇", "bat", "night vampire halloween"],
    ["🐺", "wolf", "howl pack werewolf"],
    ["🐗", "boar pig wild", "hog tusks"],
    ["🐴", "horse", "pony unicorn neigh"],
    ["🦄", "unicorn", "magic rainbow fantasy"],
    ["🐝", "bee honey", "bumble buzz insect"],
    ["🐛", "bug caterpillar", "insect worm larva"],
    ["🦋", "butterfly", "insect pretty transform"],
    ["🐌", "snail slow", "shell slug pace"],
    ["🐞", "ladybug beetle", "insect luck spots"],
    ["🐜", "ant", "insect worker tiny"],
    ["🕷️", "spider web", "arachnid halloween creepy"],
    ["🦂", "scorpion", "sting desert zodiac"],
    ["🐢", "turtle tortoise", "slow shell sea"],
    ["🐍", "snake python", "serpent slither hiss"],
    ["🦎", "lizard gecko", "reptile salamander"],
    ["🦖", "t-rex dinosaur", "dino jurassic trex"],
    ["🐙", "octopus", "sea tentacles eight"],
    ["🦑", "squid", "sea tentacles calamari"],
    ["🦐", "shrimp", "seafood prawn crustacean"],
    ["🦀", "crab", "seafood claws beach"],
    ["🐡", "blowfish puffer", "fish sea spike"],
    ["🐠", "tropical fish", "reef aquarium colorful"],
    ["🐟", "fish", "sea swim fishing"],
    ["🐬", "dolphin", "sea smart flipper"],
    ["🐳", "whale spout", "ocean giant mammal"],
    ["🦈", "shark", "jaws ocean predator"],

    // ── Food ──
    ["🍎", "red apple", "fruit healthy teacher"],
    ["🍊", "orange tangerine", "citrus fruit juice"],
    ["🍋", "lemon", "citrus sour yellow"],
    ["🍌", "banana", "fruit peel potassium"],
    ["🍉", "watermelon", "summer fruit slice"],
    ["🍇", "grapes", "fruit vine wine"],
    ["🍓", "strawberry", "berry fruit sweet red"],
    ["🫐", "blueberries", "berry fruit blue"],
    ["🍈", "melon cantaloupe", "fruit melon"],
    ["🍒", "cherries", "fruit red pair"],
    ["🍑", "peach butt", "fruit bottom thicc"],
    ["🥭", "mango", "tropical fruit"],
    ["🍍", "pineapple", "tropical fruit pizza"],
    ["🥥", "coconut", "tropical palm milk"],
    ["🥝", "kiwi fruit", "green fuzzy"],
    ["🍅", "tomato", "vegetable sauce red"],
    ["🍆", "eggplant aubergine", "vegetable purple phallic"],
    ["🥑", "avocado", "toast guacamole green"],
    ["🥦", "broccoli", "vegetable green healthy"],
    ["🥬", "leafy greens lettuce", "salad cabbage vegetable"],
    ["🌶️", "hot pepper spicy", "chili chili hot"],
    ["🌽", "corn maize", "vegetable cob yellow"],
    ["🥕", "carrot", "vegetable orange bugs"],
    ["🧄", "garlic", "clove seasoning vampire"],
    ["🧅", "onion", "layers cry vegetable"],
    ["🥔", "potato", "spud starch chips"],
    ["🍞", "bread loaf", "bakery toast carbs"],
    ["🥐", "croissant", "french bakery breakfast"],
    ["🥖", "baguette bread", "french bakery stick"],
    ["🥨", "pretzel", "twisted snack salt"],
    ["🧀", "cheese wedge", "dairy cheddar mouse"],
    ["🥚", "egg", "breakfast protein shell"],
    ["🍳", "cooking egg fried pan", "breakfast sunny side"],
    ["🥞", "pancakes stack syrup", "breakfast flapjacks"],
    ["🥓", "bacon strips", "breakfast pork crispy"],
    ["🍗", "poultry leg chicken drumstick", "meat fried bone"],
    ["🍖", "meat bone", "bbq dog bone"],
    ["🌭", "hot dog", "sausage bun street food"],
    ["🍔", "burger hamburger", "fast food beef bun"],
    ["🍟", "french fries", "fast food potato chips"],
    ["🍕", "pizza slice", "italian fast food cheese"],
    ["🥪", "sandwich", "lunch bread filling"],
    ["🌮", "taco", "mexican wrap tuesday"],
    ["🌯", "burrito wrap", "mexican roll"],
    ["🥙", "stuffed flatbread pita", "gyro kebab falafel"],
    ["🍜", "ramen noodles bowl", "japanese soup broth"],
    ["🍝", "spaghetti pasta", "italian noodles meatball"],
    ["🍣", "sushi", "japanese rice fish raw"],
    ["🍱", "bento box", "japanese lunch compartments"],
    ["🍛", "curry rice", "spicy indian dish"],
    ["🍚", "cooked rice bowl", "white grain asian"],
    ["🍥", "fish cake naruto", "ramen topping swirl"],
    ["🥠", "fortune cookie", "prophecy chinese dessert"],
    ["🍢", "oden skewer", "kebab japanese grill"],
    ["🍡", "dango dumplings", "japanese sweet skewer"],
    ["🍧", "shaved ice", "dessert snow cone syrup"],
    ["🍨", "ice cream bowl", "dessert scoop sweet"],
    ["🍦", "soft ice cream cone", "dessert sweet swirl"],
    ["🥧", "pie", "dessert pastry slice apple"],
    ["🧁", "cupcake", "dessert frosting bakery"],
    ["🍰", "cake slice shortcake", "birthday dessert strawberry"],
    ["🎂", "birthday cake candles", "party celebration years"],
    ["🍮", "custard flan pudding", "dessert caramel"],
    ["🍭", "lollipop candy", "sweet sugar swirl"],
    ["🍬", "candy sweet", "sugar wrapped treat"],
    ["🍫", "chocolate bar", "cocoa sweet treat"],
    ["🍿", "popcorn", "movie cinema snack"],
    ["🍩", "doughnut donut", "sprinkles sweet hole"],
    ["🍪", "cookie", "biscuit chocolate chip crumbs"],
    ["☕", "coffee hot", "cafe espresso morning caffeine"],
    ["🍵", "tea green cup", "matcha teapot drink"],
    ["🧋", "bubble tea boba", "pearl milk drink straw"],
    ["🥤", "cup straw soda", "drink soft fountain"],
    ["🍺", "beer mug", "drink alcohol pub cheers"],
    ["🍻", "beer cheers clink", "drinks pub friends toast"],
    ["🥂", "champagne clink glasses", "celebrate sparkling toast"],
    ["🍷", "wine glass", "red drink alcohol dinner"],
    ["🥃", "whisky tumbler", "scotch bourbon spirit"],
    ["🍸", "cocktail martini", "bar drink shaken"],
    ["🍹", "tropical drink umbrella", "cocktail vacation rum"],
    ["🧊", "ice cube", "frozen cold water"],

    // ── Activity ──
    ["⚽", "soccer ball football", "goal sport fifa"],
    ["🏀", "basketball", "sport hoop nba dunk"],
    ["🏈", "american football", "sport nfl touchdown"],
    ["⚾", "baseball", "sport mlb bat glove"],
    ["🎾", "tennis ball racket", "sport wimbledon match"],
    ["🏐", "volleyball", "sport net spike beach"],
    ["🏉", "rugby ball", "sport tackle"],
    ["🎱", "8 ball pool billiards", "game cue luck magic"],
    ["🏓", "ping pong table tennis", "sport paddle"],
    ["🏸", "badminton racket shuttlecock", "sport birdie"],
    ["🥅", "goal net hockey soccer", "keeper save sport"],
    ["🏒", "ice hockey stick puck", "sport rink nhl"],
    ["🏏", "cricket bat ball", "sport wicket"],
    ["⛳", "golf flag hole", "sport course putt"],
    ["🏹", "bow arrow archery", "target hunt cupid"],
    ["🎣", "fishing pole fish", "catch hobby angler"],
    ["🥊", "boxing glove punch", "fight sport muay"],
    ["🥋", "martial arts uniform", "karate judo taekwondo belt"],
    ["🎽", "running shirt medal", "marathon athletics bib"],
    ["🛹", "skateboard", "skating street ollie"],
    ["🛼", "roller skate", "skating wheels retro"],
    ["🎮", "video game controller", "gaming console pad play"],
    ["🕹️", "joystick arcade", "retro gaming classic"],
    ["🎲", "dice game random", "board chance roll"],
    ["🧩", "puzzle piece", "jigsaw solve fit"],
    ["♟️", "chess pawn", "strategy board game"],
    ["🎯", "dart target bullseye", "aim hit goal precision"],
    ["🎳", "bowling ball pins", "strike alley sport"],
    ["🎪", "circus tent", "carnival show big top"],
    ["🎭", "theater masks drama", "perform comedy tragedy acting"],
    ["🎨", "artist palette paint", "art colors creative design"],
    ["🎤", "microphone karaoke sing", "music performance voice podcast"],
    ["🎧", "headphones music audio", "listen sound dj"],
    ["🎼", "musical score notes sheet", "compose music notation"],
    ["🎵", "musical note", "music melody song tune"],
    ["🎶", "music notes melody", "music song notes singing"],
    ["🎹", "piano keyboard keys", "music instrument play"],
    ["🥁", "drum drumsticks band", "beat rhythm percussion"],
    ["🎸", "guitar electric", "music rock strings riff"],
    ["🎺", "trumpet brass horn", "music jazz wind"],
    ["🎻", "violin strings classical", "music fiddle bow"],
    ["🎬", "clapper board movie film", "cinema action director video"],
    ["🏆", "trophy winner award", "champion prize victory gold"],
    ["🥇", "gold medal first", "win champion number one"],
    ["🥈", "silver medal second", "runner up place"],
    ["🥉", "bronze medal third", "place award"],
    ["🎖️", "military medal ribbon", "honor award decoration"],

    // ── Travel ──
    ["🚗", "car automobile", "drive vehicle auto"],
    ["🚕", "taxi cab", "uber ride hail"],
    ["🚙", "suv car", "vehicle drive offroad"],
    ["🚌", "bus", "transit public transport school"],
    ["🚎", "trolley bus", "transit electric"],
    ["🏎️", "race car f1", "speed formula motorsport"],
    ["🚓", "police car cruiser", "cop law siren"],
    ["🚑", "ambulance emergency", "hospital medical siren"],
    ["🚒", "fire engine truck", "firefighter emergency"],
    ["🚚", "truck delivery lorry", "cargo freight haul"],
    ["🚛", "articulated truck semi", "freight trailer cargo"],
    ["🚜", "tractor farm", "agriculture field harvest"],
    ["🏍️", "motorcycle motorbike", "ride bike speed"],
    ["🛵", "motor scooter vespa", "moped delivery ride"],
    ["🚲", "bicycle bike pedal", "cycle riding sport"],
    ["🛴", "kick scooter", "ride push urban"],
    ["✈️", "airplane flight travel", "plane trip airport jet"],
    ["🚀", "rocket launch space", "ship startup blastoff spaceship"],
    ["🛰️", "satellite orbit", "space communications gps"],
    ["🚁", "helicopter chopper", "rotor flight air"],
    ["⛵", "sailboat yacht", "sea wind cruise boat"],
    ["🚢", "ship cruise liner", "ocean boat voyage titanic"],
    ["🚂", "steam locomotive train", "railway engine vintage"],
    ["🚆", "train railway", "rail transit commute"],
    ["🚄", "bullet train high speed", "shinkansen rail express"],
    ["🚇", "metro subway underground", "tube rail transit city"],
    ["🗺️", "world map", "travel navigate atlas route"],
    ["🧭", "compass navigate", "direction north magnetic explore"],
    ["🏔️", "mountain snow", "peak climb alps nature"],
    ["🌋", "volcano eruption lava", "mountain fire magma island"],
    ["🏕️", "camping tent", "outdoor nature campsite"],
    ["🏖️", "beach umbrella sand", "vacation tropical shore coast"],
    ["🏝️", "desert island", "tropical paradise castaway"],
    ["🏜️", "desert cactus", "sand dry sahara dunes"],
    ["🌅", "sunrise morning", "dawn coast day new"],
    ["🌄", "sunrise mountains", "dawn valley morning"],
    ["🌇", "sunset city dusk", "evening skyline golden hour"],
    ["🌆", "cityscape night buildings", "urban downtown skyline"],
    ["🌃", "night stars city", "evening skyline stars"],
    ["🌉", "bridge night", "span river city lights"],
    ["🎡", "ferris wheel", "fair amusement park ride"],
    ["🎢", "roller coaster", "amusement park thrill ride"],
    ["🗼", "tokyo tower", "japan landmark tokyo"],
    ["🗽", "statue liberty", "new york usa landmark freedom"],
    ["🏰", "castle european", "medieval fairy tale fort"],
    ["🏯", "japanese castle", "fortress japan historic"],
    ["🏟️", "stadium arena", "sports concert crowd venue"],
    ["⛲", "fountain water", "park coins spray plaza"],
    ["🌴", "palm tree", "tropical vacation beach island"],

    // ── Objects ──
    ["⌚", "watch wrist time", "clock fashion accessory"],
    ["📱", "mobile phone smartphone", "cell device call iphone"],
    ["💻", "laptop computer", "pc macbook work code"],
    ["⌨️", "keyboard typing", "computer input mechanical keys"],
    ["🖥️", "desktop computer monitor", "screen pc workstation display"],
    ["🖨️", "printer paper", "office print scan"],
    ["🖱️", "computer mouse click", "input pointer device"],
    ["💾", "floppy disk save", "retro storage memory"],
    ["💿", "cd disc optical", "compact music disk"],
    ["📀", "dvd disc", "movie optical disk"],
    ["📷", "camera photo", "picture snapshot lens dslr"],
    ["📸", "camera flash", "photo picture snap"],
    ["📹", "video camera", "record camcorder footage"],
    ["📺", "tv television", "screen watch series stream"],
    ["📻", "radio broadcast", "music antenna am fm"],
    ["🎙️", "studio microphone", "podcast record voice sing"],
    ["🔋", "battery full power", "energy charge cell"],
    ["🪫", "low battery empty", "energy dying charge"],
    ["🔌", "electric plug power", "socket outlet charge cable"],
    ["💡", "light bulb idea", "innovation bright idea lamp"],
    ["🔍", "magnifying glass search left", "find zoom inspect look"],
    ["🔎", "magnifying glass search right", "find zoom inspect look"],
    ["🔒", "locked padlock secure", "private password closed safety"],
    ["🔓", "unlocked padlock open", "access free unlock"],
    ["🔑", "key access unlock", "password secret door"],
    ["🗝️", "old key antique", "vintage lock skeleton"],
    ["🔨", "hammer tool build", "fix nail construction strike"],
    ["🪓", "axe chop wood", "hatchet split lumberjack"],
    ["🛠️", "hammer wrench tools", "fix repair settings maintenance"],
    ["⚙️", "gear settings cog", "options config preferences mechanics"],
    ["🧲", "magnet attract", "physics attraction magnetic"],
    ["💉", "syringe vaccine shot", "medicine injection health drug"],
    ["💊", "pill medicine capsule", "drug tablet pharmacy health"],
    ["🩹", "bandage plaster", "first aid wound heal"],
    ["🩺", "stethoscope doctor", "medical health exam checkup"],
    ["🚪", "door entrance exit", "entry open close room"],
    ["🪑", "chair seat furniture", "sit desk stool"],
    ["🛏️", "bed sleep", "rest bedroom mattress hotel"],
    ["🚽", "toilet wc bathroom", "restroom loo porcelain"],
    ["🚿", "shower bath water", "clean rinse bathroom"],
    ["🧼", "soap wash clean", "hygiene bubbles foam lather"],
    ["🧽", "sponge wipe", "clean absorb scrub dish"],
    ["🧹", "broom sweep clean", "sweeping janitor dust tidy"],
    ["🛒", "shopping cart grocery", "buy store supermarket checkout"],
    ["🎁", "gift present box", "birthday surprise wrapped give"],
    ["🎈", "balloon party float", "birthday celebration helium decor"],
    ["🎉", "party popper confetti", "celebrate congrats yay fiesta"],
    ["🎊", "confetti ball party", "celebrate festival event joy"],
    ["🎀", "ribbon bow decorative", "gift wrap pink cute"],
    ["📦", "package parcel box", "shipping delivery cardboard unboxing"],
    ["📚", "books study stack", "library reading education learn"],
    ["📖", "open book reading", "novel story literature pages"],
    ["📝", "memo write note pencil", "note taking compose jot"],
    ["✏️", "pencil draw write", "edit sketch stationery graphite"],
    ["🖊️", "pen write", "ink signature biro"],
    ["📅", "calendar date schedule", "day month planner appointment"],
    ["📊", "bar chart stats data", "analytics graph report metrics"],
    ["📈", "chart increasing growth", "up trend stocks graph rise"],
    ["📉", "chart decreasing loss", "down trend stocks graph fall"],
    ["💰", "money bag cash rich", "coins wealth salary sack"],
    ["💵", "dollar banknote money usd", "cash bill currency"],
    ["💳", "credit card payment", "bank debit buy visa"],
    ["🪙", "coin money gold", "currency metal cents bitcoin"],
    ["💎", "gem diamond jewel", "precious luxury rare crystal"],
    ["⚖️", "balance scale justice", "law court weigh legal"],
    ["🔧", "wrench fix tool", "repair adjust mechanic spanner"],
    ["🪛", "screwdriver tool", "turn screws repair phillips"],
    ["🔩", "nut bolt hardware", "fasten metal thread screw"],
    ["🔗", "link chain url", "connect hyperlink web attach"],
    ["📎", "paperclip attach file", "clip office stationery hold"],
    ["✂️", "scissors cut craft", "shears trim snip divide"],
    ["📌", "pushpin pin mark", "location attach note important"],
    ["🗑️", "trash bin waste", "delete garbage rubbish discard"],
    ["🧯", "fire extinguisher safety", "emergency flame suppress put out"],
    ["🛡️", "shield defense protect", "guard armor security block"],
    ["⚔️", "crossed swords battle", "fight war blades duel combat"],
    ["🔫", "water pistol toy", "squirt gun nerf play"],

    // ── Symbols ──
    ["❤️", "red heart love", "valentine passion like romantic"],
    ["🧡", "orange heart", "affection warm autumn"],
    ["💛", "yellow heart", "friendship sunny gold"],
    ["💚", "green heart", "nature envy healthy eco"],
    ["💙", "blue heart", "calm loyal trust stable"],
    ["💜", "purple heart", "violet lavender dracula"],
    ["🖤", "black heart dark", "goth morbid emo void"],
    ["🤍", "white heart pure", "clean minimal innocent"],
    ["💔", "broken heart sad", "breakup divorce heartache lost"],
    ["❣️", "heart exclamation", "love emphasis valentine"],
    ["💕", "two hearts love", "couple affection romance together"],
    ["💞", "revolving hearts", "love spinning couple romance"],
    ["💓", "beating heart pulse", "love heartbeat alive excited"],
    ["💗", "growing heart", "love growing affection pink"],
    ["💖", "sparkling heart", "love sparkle cute shine"],
    ["💘", "heart arrow cupid", "valentine love shot romance"],
    ["💝", "heart ribbon gift", "love present valentines give"],
    ["💯", "hundred points perfect", "score keep it real 100 percent"],
    ["💥", "collision boom explosion", "bang crash impact comic"],
    ["💫", "dizzy stars sparkle", "shimmer magic disney woozy"],
    ["💦", "sweat droplets splash", "water rain drops wet"],
    ["💨", "dash away wind fast", "speed gust puff run"],
    ["🕳️", "hole void empty", "pit gap abyss black"],
    ["💬", "speech balloon comment", "chat message talk bubble text"],
    ["💭", "thought balloon dream", "thinking idea imagine cloud"],
    ["🗯️", "anger bubble shout", "rant yell speech rage"],
    ["💤", "zzz sleep snore", "sleeping dreams tired rest"],
    ["✅", "check mark done complete", "yes correct ok verified pass"],
    ["☑️", "checkbox checked", "done selected task vote yes"],
    ["✔️", "heavy check confirm", "tick right ok pass"],
    ["❌", "cross x wrong no", "fail cancel incorrect close delete"],
    ["❎", "cross button reject", "no deny cancel wrong"],
    ["➕", "plus add math", "positive more create new"],
    ["➖", "minus subtract", "negative less remove delete"],
    ["➗", "divide math split", "division share calculate"],
    ["✖️", "multiply times close", "multiplication math cancel"],
    ["♾️", "infinity eternal loop", "forever unlimited endless boundless"],
    ["⚡", "high voltage lightning zap", "power energy flash electric fast"],
    ["🔥", "fire flame lit hot", "burn trending lit smoke blaze"],
    ["🌈", "rainbow pride colors", "arc spectrum hope weather lgbt"],
    ["☀️", "sun sunny clear", "bright day weather hot summer"],
    ["⛅", "partly cloudy sun", "weather clouds fair sky"],
    ["☁️", "cloud weather overcast", "sky gray gloomy fluffy"],
    ["🌧️", "rain cloud wet", "weather rainy storm drizzle"],
    ["⛈️", "thunderstorm lightning rain", "storm weather bolt severe"],
    ["❄️", "snowflake winter cold", "ice freeze frost snow crystal"],
    ["🌊", "wave ocean sea water", "surf tide tsunami blue"],
    ["🌟", "glowing star shine", "sparkle special bright favorite"],
    ["⭐", "star favorite rate", "gold rating bookmark night"],
    ["✨", "sparkles magic clean", "shine glitter special aesthetic new"],
    ["🎉", "tada party celebrate", "congrats hooray celebration event"],
    ["🔔", "bell notification ring alert", "alarm remind sound attention"],
    ["🔕", "bell muted silent", "notification off do not disturb"],
    ["🎵", "note beat music", "melody song audio track"],
    ["🕐", "one oclock clock time", "hour schedule watch"],
    ["⏰", "alarm clock wake", "timer morning reminder alert"],
    ["⏳", "hourglass sand timer wait", "loading time patience countdown"],
    ["⌛", "hourglass done timeout", "time up expired sand finish"],
    ["🔴", "red circle dot record", "live recording stop warning"],
    ["🟠", "orange circle dot", "medium round color"],
    ["🟡", "yellow circle dot", "warning medium round"],
    ["🟢", "green circle dot go", "online success ready active"],
    ["🔵", "blue circle dot", "info round calm"],
    ["🟣", "purple circle dot violet", "dracula lavender round"],
    ["⚫", "black circle dark", "round midnight void"],
    ["⚪", "white circle light", "round clean minimal"],
    ["🔺", "red triangle up", "increase warning delta raise"],
    ["🔻", "red triangle down", "decrease drop lower fall"],
    ["💠", "diamond shape blue", "decorative geometric pixel"],
    ["🔶", "orange diamond large", "geometric shape amber"],
    ["🔷", "blue diamond large", "geometric shape azure"],
    ["♻️", "recycle reuse eco", "environment green sustainable arrows"],
    ["🔞", "18 adult restriction", "nsfw mature age limit"],
    ["🆗", "ok button agree", "accept fine approved"],
    ["🆒", "cool button", "new awesome chill"],
    ["🆕", "new badge fresh", "recent latest update release"],
    ["🆙", "upgrade level up", "update improve version increase"],
    ["🈶", "japanese have", "kanji exist owned"],
    ["🚫", "prohibited forbidden no", "ban denied blocked restricted"],
    ["⚠️", "warning caution alert", "careful danger hazard attention"],
    ["🚸", "children crossing kids", "school zone pedestrian careful"],
    ["🔱", "trident poseidon", "pitchfork sea god anchor emblem"],
    ["⚜️", "fleur de lis royal", "lily france heraldry emblem"],
    ["🔰", "beginner japan leaf", "newbie novice start japanese"],
    ["✳️", "asterisk star note", "footprint reference symbol six"],
    ["❇️", "sparkle flare shine", "glitter twinkle clean new"],
    ["©️", "copyright copyright", "legal rights license ip"],
    ["®️", "registered trademark", "brand legal license ip"],
    ["™️", "trademark tm brand", "legal license intellectual"]
];

// de-dup accidental duplicate chars (defensive — keeps grid honest)
const seen = {};
const entries = emoji.filter(e => {
    if (seen[e[0]])
        return false;
    seen[e[0]] = true;
    return true;
});

function search(query) {
    const q = query.trim().toLowerCase();
    if (q.length === 0)
        return entries;
    return entries.filter(e => (e[1] + " " + e[2]).includes(q));
}
