#+title: packages
#+startup: content indent

* justinVC-tech :justin:
#+begin_src emacs-lisp :tangle no
(package! random-splash-image
          :recipe (:host github :repo "kakakaya/random-splash-image"))

;; (package! gptel)
;; (package! gptel-quick :recipe (:host github :repo  "karthink/gptel-quick"))

#+end_src

* DOCS
** install pkg
*** melpa
To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
#+begin_src elisp
(package! some-package)
#+end_src

*** git

To install a package directly from a remote git repo, you must specify a
=:recipe=.

You'll find documentation on what `:recipe' accepts here:
https://github.com/radian-software/straight.el#the-recipe-format

#+begin_src elisp
(package! another-package
  :recipe (:host github :repo "username/repo"))
#+end_src

If the package you are trying to install does not contain a =PACKAGENAME.el= file,
or is located in a subdirectory of the repo, you'll need to specify =:files= in the =:recipe=:

#+begin_src elisp
(package! this-package
  :recipe (:host github :repo "username/repo"
           :files ("some-file.el" "src/lisp/*.el")))
#+end_src

** disable doom pkgs

If you'd like to disable a package included with Doom, you can do so here
with the =:disable= property:

#+begin_src elisp
(package! builtin-package :disable t)
#+end_src

My Disabled Packages
#+begin_src elisp
(package! company :disable t)
(package! helm :disable t)
#+end_src

** override pkgs

You can override the recipe of a built in package without having to specify
all the properties for =`:recipe'=.

These will inherit the rest of its recipe from Doom or MELPA/ELPA/Emacsmirror:

#+begin_src elisp
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))
#+end_src

Specify a =`:branch'= to install a package from a particular branch or tag.

This is required for some packages whose default branch isn't 'master' (which
our package manager can't deal with; see radian-software/straight.el#279)

#+begin_src elisp
(package! builtin-package :recipe (:branch "develop"))
#+end_src

Use =`:pin'= to specify a particular commit to install.
Doom's packages are pinned to a specific commit and updated from release to release.

#+begin_src elisp
(package! builtin-package :pin "1a2b3c4d5e")
#+end_src


The =`unpin!'= macro allows you to unpin single packages...

#+begin_src elisp
(unpin! pinned-package)
;;...or multiple packages
(unpin! pinned-package another-pinned-package)
;;...Or *all* packages (NOT RECOMMENDED; will likely break things)
(unpin! t)
#+end_src


Whenever you reconfigure a package, make sure to wrap your config in an
 =after!= block, otherwise Doom's defaults may override your settings. E.g.

 #+begin_src elisp
(after! PACKAGE
  (setq x y))
 #+end_src

 The exceptions to this rule:
   + Setting =file/directory= variables (like `org-directory')
   + Setting =variables= which explicitly tell you to set them =before their
     package is loaded= (see 'C-h v VARIABLE' to look up their documentation).
   + Setting =doom variables= (which start with =doom-= or =+=).

 Here are some additional functions/macros that will help you configure Doom.
 + =load!= for loading external *.el files relative to this one
 + =use-package!= for configuring packages
 + =after!= for running code after a package has loaded
 + =add-load-path!= for adding directories to the `load-path', relative to
   this file. Emacs searches the `load-path' when you load packages with
   =require= or =use-package=.
 + =map!= for binding new keys

** extra
 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
 This will open documentation for it, including demos of how they are used.
 Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
 etc).

 You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
 they are implemented.
